/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndk_practice_FibLib */

#ifndef _Included_com_example_ndk_practice_FibLib
#define _Included_com_example_ndk_practice_FibLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndk_practice_FibLib
 * Method:    fabIterativeNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_example_ndk_1practice_FibLib_fabIterativeNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_ndk_practice_FibLib
 * Method:    fabRecursionNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_example_ndk_1practice_FibLib_fabRecursionNative
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
